### ISSUE TITLE
Command 'Arduino-CLI: Compile' resulted in an error (Cannot read property 'fqbn' of undefined)

### ISSUE THREAD

**Issue by trullock** [PeterWone/vscode-arduino-cli#9]
Probably because I dont have a board selected

**Comment by PeterWone** [comment]
While we could hide compile and deploy until a board is selected, I think it would help the user more if they announced the fact that a board selection is required along with a link into the wiki.

**Comment by trullock** [comment]
Yeah dont hide UI because of state, it completely hampers discoverability
